apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: claw-commons

resources:
  - ../../base
  - secrets

patches:
  - path: route.yaml

configMapGenerator:
  - name: claw-commons-config
    behavior: replace
    files:
      - openclaw.json

generatorOptions:
  disableNameSuffixHash: true
