apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - serviceaccount.yaml
  - persistentvolumeclaim.yaml
  - deployment.yaml
  - service.yaml
  - route.yaml

configMapGenerator:
  - name: claw-commons-config
    files:
      - openclaw.json

generatorOptions:
  disableNameSuffixHash: true
