apiVersion: v1
kind: ServiceAccount
metadata:
  name: claw-commons
  labels:
    app.kubernetes.io/name: claw-commons
  annotations:
    serviceaccounts.openshift.io/oauth-redirectreference.primary: '{"kind":"OAuthRedirectReference","apiVersion":"v1","reference":{"kind":"Route","name":"claw-commons"}}'
automountServiceAccountToken: true
